version: '3.7'

volumes:
  postgres_db:
  pgadmin:

services:
  waitfordb:
    image: dadarek/wait-for-dependencies
    depends_on:
      - postgresql
    command: postgresql:5432

  postgresql:
    image: postgres:latest
    container_name: postgresql
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data/:rw
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: mlflow-db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgresql
    restart: always
    
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    ports:
      - 15432:80
    environment:
      - GUNICORN_THREADS=10
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
        - pgadmin:/root/.pgadmin
    depends_on:
      - postgresql
    restart: unless-stopped


  mlflow:
    build: .
    container_name: mlflow
    ports:
      - 8643:80
    depends_on:
      - postgresql
      - waitfordb
    links:
      - postgresql
    # volumes:
    #   - ${LOCAL_FS_PATH}:/home/:rw
    environment:
      DB_URI: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/mlflow-db
      LOCAL_FS_PATH: ${LOCAL_FS_PATH}
      VIRTUAL_HOST: ${HOST}
      VIRTUAL_PORT: 80
    hostname: mlflow_server
    restart: always
